### ISSUE TITLE
1.72.0

### ISSUE THREAD

**Issue by mumbleskates** [iceboy233/boost#6]
Are there any blockers to bumping the version? Doesn't look like it from the release notes. https://www.boost.org/users/history/version_1_72_0.html

**Comment by iceboy233** [comment]
There are no blockers to bumping the version. Bumping the version can break certain libraries for change in dependencies and we need to fix them if we find the breakage, but we would only know after we bumped the version since we don't have tests in this repo yet.

Feel free to create a PR to bump the version or make other improvements.
